# Generated by Django 4.2.3 on 2023-07-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ci',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
